[versions]
jackson = "2.20.1"

[libraries]
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.21.0" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
angus-mail = { group = "org.eclipse.angus", name = "angus-mail", version = "2.0.5" }
bcrypt = { group = "de.svenkubiak", name = "jBCrypt", version = "0.4.3" }
reflections = { group = "org.reflections", name = "reflections", version = "0.10.2" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.42" }
spock = { group = "org.spockframework", name = "spock-core", version = "2.4-groovy-5.0" }
logback = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.23" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
sonarqube = { id = "org.sonarqube", version = "7.0.1.6134" }